# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20171102_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdata',
            name='pct_diabetes',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_obese',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
