# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20171102_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessdata',
            old_name='pct_access',
            new_name='amerindian_2010',
        ),
        migrations.RenameField(
            model_name='accessdata',
            old_name='pct_diabetes',
            new_name='asian_2010',
        ),
        migrations.RenameField(
            model_name='accessdata',
            old_name='pct_obese',
            new_name='black_2010',
        ),
        migrations.AddField(
            model_name='accessdata',
            name='convenience_2009',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='convenience_2014',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='grocery_2009',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='grocery_2014',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='hawaiian_2010',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='hispanic_2010',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_access_2010',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_access_2015',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_diabetes_2008',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_diabetes_2013',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_obese_2008',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_obese_2013',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='supercenter_2009',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='supercenter_2014',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessdata',
            name='white_2010',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
    ]
