# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_auto_20171107_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable1', models.CharField(max_length=20)),
                ('variable2', models.CharField(max_length=20)),
                ('correlation', models.FloatField(max_length=5)),
            ],
        ),
    ]
