# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_correlationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdata',
            name='amerindian_2010',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='asian_2010',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='black_2010',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='convenience_2009',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='convenience_2014',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='grocery_2009',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='grocery_2014',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='hawaiian_2010',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='hispanic_2010',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='pct_access_2010',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='pct_access_2015',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='pct_diabetes_2008',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='pct_diabetes_2013',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='pct_obese_2008',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='pct_obese_2013',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='supercenter_2009',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='supercenter_2014',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='white_2010',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='lower_bound',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='upper_bound',
            field=models.FloatField(max_length=20),
        ),
    ]
