# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_auto_20171117_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='variable',
            field=models.CharField(max_length=25),
        ),
    ]
