# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_auto_20171119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlationdata',
            name='correlation',
            field=models.FloatField(),
        ),
    ]
