# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_auto_20171119_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlationdata',
            name='correlation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
