# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_auto_20171119_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdata',
            name='pct_snap12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_snap16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_wic09',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='pct_wic15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='snap_redemption12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='snap_redemption16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='wic_redemption08',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='wic_redemption12',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
